# Generated by Django 6.1.1 on 2026-09-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='categoria',
            field=models.CharField(choices=[('Entrada', 'Entrada'), ('Principal', 'Prato Principal'), ('Sobremesa', 'Sobremesa'), ('Bebida', 'Bebida')], default='Principal', max_length=20),
        ),
    ]
